import streamlit as st
import numpy as np
from PIL import Image
image1 = Image.open('1.png')
image2 = Image.open('2.png')
image3 = Image.open('3.png')
image4 = Image.open('4.png')
image5 = Image.open('5.png')
image6 = Image.open('6.png')
image7 = Image.open('7.png')
image8 = Image.open('8.png')
image9 = Image.open('9.png')
image10 = Image.open('10.png')
image11 = Image.open('11.png')
image12 = Image.open('12.png')
image13 = Image.open('13.png')
image14 = Image.open('14.png')

st.title('Club 3')
st.write('En este club exploraremos posibilidades alternas para el desarollo de farmacos novedosos contra infecciones virales y bacterianas, basandonos en aproximaciones bioinformaticas')
st.write('In this club we are going to explore alternative possibilites for developing novel drugs against viral and bacterial infecitions based in bioinfrmatics approaches')  

#Seccion 1: Nuestro Club/Our Club
my_page = st.sidebar.radio("Página de navegación", ["Biologia molecular/ Molecular Biology", "Proteinas/Proteins", "Resistencia antimicrobiana/Antimicrobial resistance", "COVID-19", "Referencias bibliográficas"])
st.write('')
st.write('')
st.write('')
st.image(image1)
st.write('')
st.write('')
st.image(image2)
st.write('')
st.write('')
st.image(image3)
st.write('')
st.write('')
st.image(image4)
st.write('')
st.write('')
st.image(image5)
st.write('')
st.write('')
st.image(image6)
st.write('')
st.write('')
st.image(image7)
st.write('')
st.write('')
st.image(image8)
st.write('')
st.write('')
st.image(image9)
st.write('')
st.write('')
st.image(image10)
st.write('')
st.write('')
st.image(image11)
st.write('')
st.write('')
st.image(image12)
st.write('')
st.write('')
st.image(image13)
st.write('')
st.write('')
st.image(image14)
st.write('')
st.write('')
